version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "placeIt"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    image: chinmay1104/backend:latest
    container_name: backend_container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql_container:3306/placement_portal"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "cp12345six"

  frontend:
    image: chinmay1104/frontend:latest
    container_name: frontend_container
    ports:
      - "3000:3000"    

volumes:
  mysql_data:

# Add other configurations as required

