---
- name: Pull Docker Images and Run Docker Compose
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull MySQL image
      docker_image:
        name: mysql:latest
        source: pull
      become: yes
      become_method: sudo

    - name: Pull backend image
      docker_image:
        name: kritinp/backend:latest
        source: pull
      become: yes
      become_method: sudo

    - name: Pull frontend image
      docker_image:
        name: kritinp/frontend:latest
        source: pull
      become: yes
      become_method: sudo
    
    - name: Run Docker Compose
      command: docker-compose -f ../docker-compose.yml up -d
      become: yes
      become_method: sudo